version: '3.3'

services:
  rctg-db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password1!
      - MYSQL_DATABASE=rctg
    ports:
      - '3306:3306'
    volumes:
      - /data/rctg/volume/mysql:/var/lib/mysql

  rctg-server:
    build:
      context: .
      dockerfile: DockerfileServer
    ports:
      - '8080:8080'
    depends_on:
      - rctg-db
    restart: on-failure

  rctg-client:
    build:
      context: .
      dockerfile: DockerfileClient
    ports:
      - 80:80
    depends_on:
      - rctg-server
