spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rctg-db:3306/rctg?serverTimezone=UTC
    username: root
    password: password1!
server:
#  address: 192.168.1.10
#  port: 8080
